GET http://localhost:3002/api/query1

###
GET  http://localhost:3002/api/query12/1/2022-04-11

###
GET http://localhost:3002/api/query3

###
GET http://localhost:3002/api/query4

###
GET http://localhost:3002/api/query5

###
GET http://localhost:3002/api/query6

###
GET http://localhost:3002/api/query7

###
GET http://localhost:3002/api/query8

###
GET http://localhost:3002/api/query9

###
GET http://localhost:3002/api/query10

###
GET http://localhost:3002/api/query11

###
GET  http://localhost:3002/api/query12/2022-04-11/2023-10-26