POST http://localhost:3002/api/client/create
Content-Type: application/json

{
    "ClientID": 11,
    "firstname":"Johannes", 
    "surname":"Dreat", 
    "weight":"56.5", 
    "height":"1.56",  
    "sex":"M", 
    "age":27,
    "telephone":"212-818-8382"
}

###
DELETE http://localhost:3002/api/client/11

###
GET http://localhost:3002/api/query1



###
GET http://localhost:3002/api/query3

###
GET  http://localhost:3002/api/query4/2022-10-26

###
GET http://localhost:3002/api/query5

###
GET http://localhost:3002/api/query6

###
GET http://localhost:3002/api/query7

###
GET http://localhost:3002/api/query8

###
GET http://localhost:3002/api/query9

###
GET http://localhost:3002/api/query10

###
GET http://localhost:3002/api/query11

###
GET  http://localhost:3002/api/query12/2022-04-11

###
GET  http://localhost:3002/api/query13/2022-04-11/2023-10-26